language: python
python:
  - "3.5"
install: "pip install requests pyyaml jinja2 sqlalchemy pyparsing gitbib"
script: "gitbib ."

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master