language: python
python:
  - "3.5"
install: "pip install requests pyyaml jinja2 sqlalchemy pyparsing gitbib"
script: "gitbib -c cache/gitbib.sqlite ."

cache:
  directories:
    - cache

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: gitbib